<?php

namespace App\Repositories\Product\Attribute;

use App\Models\Product\Attribute;
use App\Repositories\BaseRepository;

class CreateAttribute extends BaseRepository
{
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function execute(array $data) : Attribute
    {
        $this->validate($data);

        $attribute = Attribute::create();
    }
}
