<?php

namespace App\Repositories\Product\Attribute;

use App\Models\Product\Attribute;
use App\Repositories\BaseRepository;
use Illuminate\Support\Facades\DB;

class CreateAttribute extends BaseRepository
{
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function execute(array $data) : Attribute
    {
        $this->validate($data);

        DB::transaction(function () use (&$data){
            $attribute = Attribute::create([
                'attribute_name' => $data['attribute_name'],
                'enterprise_id' => $data['enterprise_id'],
                'is_disable' => $data['is_disable'],
            ]);

            if(isset($data['specs'])){
                $data['specs'] = json_decode($data['specs'],true);
                $attribute->specs()->createMany($data['specs']);
            }

            $data['id'] = $attribute->id;
        });

        return Attribute::find($data['id']);
    }
}
