<?php

namespace App\Repositories\Product\Attribute;

use App\Models\Product\AttributeSpec;
use App\Repositories\BaseRepository;

class CreateAttributeSpec extends BaseRepository
{
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function execute(array $data) : AttributeSpec
    {
        $this->validate($data);

        $spec = AttributeSpec::create([
            'attribute_id' => $data['attribute_id'],
            'spec_name' => $data['spec_name'],
        ]);

        return AttributeSpec::find($spec->id);
    }

    //
}
