<?php

namespace App\Repositories\Auth;

use App\Models\User\User;
use App\Repositories\BaseRepository;

class CreateUser extends BaseRepository
{
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function execute(array $data) : User
    {
        $this->validate($data);
        $user = User::create([
            'name' => $data['name'],
            'email' => $data['email'],
            'mobile' => $data['mobile'],
            'password' => bcrypt($data['password']),
        ]);

        return User::find($user->id);
    }
}
